---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 
  - src: git@github.com:drewplonq/vector.git
    scm: git
    name: vector 
  - src: git@github.com:drewplonq/lighthouse-role.git
    scm: git
    name: lighthouse 
